### ISSUE TITLE
How to get MatchID after BOT leaves the lobby.

### ISSUE THREAD

**Issue by JasonMcz** [Arcana/node-dota2#396] opened 2016-12-18 16:53 UTC
Currently, bot can use an event listener using LobbyID to listen players joining the game and analyzing the promise of how many people in the lobby, but is there a smart way to get matchID after Bot leaves the lobby after creating it and send invites? so it can get the result?

**Comment by JasonMcz** [comment] 2016-12-18 16:54
@Crazy-Duck @paralin

**Comment by Crazy-Duck** [comment] 2016-12-18 17:50
Duplicate of #395

**Closed** 2016-12-18 17:50 UTC
